### ISSUE TITLE
Disabling gestures

### ISSUE THREAD

**Issue by GabeeCoding** [moehriegitt/NeatLauncher#1]
Hello,

I found your launcher on F-droid and I am enjoying it so far.

My only issue is that the swipe gestures are too sensitive and I am getting unexpectedly sent to contacts,settings app

Can you add a setting to disable the gestures? Cheeers

**Comment by moehriegitt** [comment]
For this purpose, there is a 'Nothing' (pseudo) app that you can pin to the swipe actions.

(And I will still check whether the sensitivity of the gestures can be adjusted a bit.)

**Comment by moehriegitt** [comment]
Disabling is implemented via 'Nothing' => close.
