### ISSUE TITLE
analog clock weather combo?!

### ISSUE THREAD

**Issue by bobblkabb** [moehriegitt/NeatLauncher#11]
There's an option "rain on analog clock". How does this work?
And what about the opened up circle around the analog clock?

**Comment by moehriegitt** [comment]
That circle is the rain prognosis.  It will show, for the next ten hours (IIRC), a coloured line on the analog clock on those hours (or quarter hours really) where the prognosis says that there will likely be rain.  It's a visualisation of what the weather servers says about rain, in 15-minute steps, for the next ten hours.
