### ISSUE TITLE
Custom widgets

### ISSUE THREAD

**Issue by 2br-2b** [moehriegitt/NeatLauncher#5]
Hello! First off, thank you so much for this cool launcher!

On the top of the screen, it'd be really nice if I could add custom widgets. Yes, it'd kind of go against the minimalist vibe, but it'd be really nice to be able to put my calendar there (for example) without your having to implement it yourself.

I know that "no widget support" is listed as a feature, but I think it could be helpful. If not, though, I get that you're going for a minimalist app!

**Comment by ifearthelord** [comment]
You can always tap where the date appears to view the calendar.

**Comment by moehriegitt** [comment]
Thanks for the nice words!

As you already identified, I do not plan to add widget support. It is quite a complex thing to implement and get right.

I do have some ideas for displaying the next few calender events in some future version, maybe, but not as a widget.

**Comment by moehriegitt** [comment]
Sorry, indeed widgets are not in line with my notion of simplicity.

**Comment by 2br-2b** [comment]
Don't worry - I get it. I had been thinking it'd be nice to have immediate access to upcoming events, tasks, and to see the current media playing (maybe something like what some other launchers have - I can get specific ones if you want), but widgets would certainly make things more complex 🙂

**Comment by ifearthelord** [comment]
> Don't worry - I get it. I had been thinking it'd be nice to have immediate access to upcoming events, tasks, and to see the current media playing (maybe something like what some other launchers have - I can get specific ones if you want), but widgets would certainly make things more complex 🙂

This would just make the launcher more bloated
